sudo: required

language: c++

before_install:
- sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libassimp-dev
- dpkg -L libassimp-dev
- 	wget -O VulkanSDK.run https://vulkan.lunarg.com/sdk/download/1.0.61.0/linux/vulkansdk-linux-x86_64-1.0.61.0.run?human=true && chmod ugo+x VulkanSDK.run
- ./VulkanSDK.run

script:
   - export VULKAN_SDK="${PWD}/VulkanSDK/1.0.61.0/x86_64"
   - export PATH="${VULKAN_SDK}/bin:${PATH}"
   - git submodule update --init
   - cmake -DCMAKE_BUILD_TYPE=Release
   - make

